### ISSUE TITLE
Decipher

### ISSUE THREAD

**Issue by BennerLukas** [BennerLukas/Moerser#2]
- dot/dash to binary
- binary to alphabet
- error correction 
- grammatic correction (Groß und Kleinschreibung) (-> Mini NLP)
- (Word correction?)

**Comment by Madhour** [comment]
(1. Sync Start of Transmission)
2. Detect Blinking in Image
3. Interpret Blinking into Dit/Dash

**Comment by BennerLukas** [comment]
- [ ] get binary (Flankenwechselding)
- [ ] search for sync pattern -> or analyze the sequence
- [ ]

**Comment by BennerLukas** [comment]
... --- ...

101010 000

101010 000 1110 1110 000  1110 101010
S                      O                          S

1,1,1, 111, 111, 111, 1,1,1

WWWWWWBWBWBWWWBBBWBBBWBBBW

**Comment by Madhour** [comment]
Brightness decoding implemented in commit bb087aa.

Current challenges:
- Need better differentiation between bright and dark (threshold works subpar)
- Find out optimal framerate for smooth decoding
