### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by BennerLukas** [BennerLukas/Moerser#6]
- Cameralivestream
- Sync/ Init Button -> Brightness baseline
- Live Übersetzung nach jedem " " (Morse2Text)
  - inkl. Errorhandlimg (mit Unterstrich)
  - Button Analyze Sequence (Pattern matchen; ähnliche Morsesequenz) (ggf. mit NLP?) -> Fuzzy Matching
- Button (Text2MorseLight) (Textbox)
- show current morse sequence (.--.-... ..---.)
- show counter (Dark, Bright)

**Comment by Madhour** [comment]
GUI:
- User can change parameters:
  - Length of sequence
  - Threshold
  - ...
